import type { Poi } from '../../types'
import { featuredPois } from './featured'
import { northPois } from './north'
import { eastPois } from './east'
import { southPois } from './south'
import { centralPois } from './central'
import { southwestPois } from './southwest'
import { northwestPois } from './northwest'
import { northeastPois } from './northeast'

// Generated by scripts/build-generated-pois.mjs. Do not edit manually.
export const generatedPois: Poi[] = [
  ...featuredPois,
  ...northPois,
  ...eastPois,
  ...southPois,
  ...centralPois,
  ...southwestPois,
  ...northwestPois,
  ...northeastPois,
]

export { featuredPois } from './featured'
export { northPois } from './north'
export { eastPois } from './east'
export { southPois } from './south'
export { centralPois } from './central'
export { southwestPois } from './southwest'
export { northwestPois } from './northwest'
export { northeastPois } from './northeast'
