import type { Poi } from '../../types'
import { pois as featuredPois } from './featured'
import { pois as p12Pois } from './p12'
import { pois as p13Pois } from './p13'
import { pois as p14Pois } from './p14'
import { pois as p15Pois } from './p15'
import { pois as p21Pois } from './p21'
import { pois as p22Pois } from './p22'
import { pois as p23Pois } from './p23'
import { pois as p32Pois } from './p32'
import { pois as p33Pois } from './p33'
import { pois as p34Pois } from './p34'
import { pois as p35Pois } from './p35'
import { pois as p36Pois } from './p36'
import { pois as p37Pois } from './p37'
import { pois as p41Pois } from './p41'
import { pois as p42Pois } from './p42'
import { pois as p43Pois } from './p43'
import { pois as p44Pois } from './p44'
import { pois as p45Pois } from './p45'
import { pois as p46Pois } from './p46'
import { pois as p50Pois } from './p50'
import { pois as p51Pois } from './p51'
import { pois as p52Pois } from './p52'
import { pois as p53Pois } from './p53'
import { pois as p54Pois } from './p54'
import { pois as p61Pois } from './p61'
import { pois as p62Pois } from './p62'
import { pois as p63Pois } from './p63'
import { pois as p64Pois } from './p64'
import { pois as p65Pois } from './p65'

// Generated by scripts/build-generated-pois.mjs. Do not edit manually.
export const generatedPois: Poi[] = [
  ...featuredPois,
  ...p12Pois,
  ...p13Pois,
  ...p14Pois,
  ...p15Pois,
  ...p21Pois,
  ...p22Pois,
  ...p23Pois,
  ...p32Pois,
  ...p33Pois,
  ...p34Pois,
  ...p35Pois,
  ...p36Pois,
  ...p37Pois,
  ...p41Pois,
  ...p42Pois,
  ...p43Pois,
  ...p44Pois,
  ...p45Pois,
  ...p46Pois,
  ...p50Pois,
  ...p51Pois,
  ...p52Pois,
  ...p53Pois,
  ...p54Pois,
  ...p61Pois,
  ...p62Pois,
  ...p63Pois,
  ...p64Pois,
  ...p65Pois,
]

export { pois as featuredPois } from './featured'
export { pois as p12Pois } from './p12'
export { pois as p13Pois } from './p13'
export { pois as p14Pois } from './p14'
export { pois as p15Pois } from './p15'
export { pois as p21Pois } from './p21'
export { pois as p22Pois } from './p22'
export { pois as p23Pois } from './p23'
export { pois as p32Pois } from './p32'
export { pois as p33Pois } from './p33'
export { pois as p34Pois } from './p34'
export { pois as p35Pois } from './p35'
export { pois as p36Pois } from './p36'
export { pois as p37Pois } from './p37'
export { pois as p41Pois } from './p41'
export { pois as p42Pois } from './p42'
export { pois as p43Pois } from './p43'
export { pois as p44Pois } from './p44'
export { pois as p45Pois } from './p45'
export { pois as p46Pois } from './p46'
export { pois as p50Pois } from './p50'
export { pois as p51Pois } from './p51'
export { pois as p52Pois } from './p52'
export { pois as p53Pois } from './p53'
export { pois as p54Pois } from './p54'
export { pois as p61Pois } from './p61'
export { pois as p62Pois } from './p62'
export { pois as p63Pois } from './p63'
export { pois as p64Pois } from './p64'
export { pois as p65Pois } from './p65'
